name: Triggered by another workflow run!
on:
  workflow_run:
    workflows: ["Manually triggered workflow"]
    types: 
      - completed
jobs:
  run_me:
    # Job name is Greeting
    name: Triggered from another workflow
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello!"
